server:
  port: 8080

spring:
  #Profile setting
  profiles:
    active: prod

  #DataSource settings
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/project-01
    username: artteam
    password: artteam