version: '2'

services:

  postgres:
    container_name: "postgres"
    build:
      context: postgres/
      dockerfile: Dockerfile
    volumes:
      - pgsql-volume:/var/lib/postgresql/data
    networks:
      - devpav
    ports:
      - "5432:5432"
    env_file:
      - .env


  rest:
    container_name: "rest"
    build:
      context: java/
      dockerfile: Dockerfile
      args:
        TOKEN_GIT: ${TOKEN_GIT}
        USERNAME_GIT: ${USERNAME_GIT}
        TAG_SERVER: ${TAG_SERVER}
        REPOSITORY_SERVER: ${REPOSITORY_SERVER}
        PROFILE_SERVER: ${PROFILE_SERVER}
        VERSION_SERVER: ${VERSION_SERVER}
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - rest-volume:/app/
    networks:
      - devpav


  nginx:
    container_name: "nginx"
    build:
      context: nginx/
      dockerfile: Dockerfile
      args:
        TOKEN_GIT: ${TOKEN_GIT}
        USERNAME_GIT: ${USERNAME_GIT}
        TAG_CLIENT: ${TAG_CLIENT}
        REPOSITORY_CLIENT: ${REPOSITORY_CLIENT}
        ENV_CLIENT: ${ENV_CLIENT}
    networks:
      - devpav
    ports:
      - "80:80"
    env_file:
      - .env
    depends_on:
      - rest


networks:
  devpav:
    driver: bridge

volumes:
  pgsql-volume:
  rest-volume:
