version: '3'

services:
    postgres:
        container_name: 'postgres_rest'
        build: postgres/
        volumes:
            - postgres-volume:/var/lib/postgresql/data
        restart: 
            unless-stopped
        networks:
            - mynet
        ports:
            - "5432:5432"
        env_file:
            - .env
    rest:
        container_name: 'rest'
        build:
            context: .
            dockerfile: Dockerfile
            args:
                username: ${USERNAME}
                password: ${PASSWORD}
                tag: ${TAG}
                repository: ${REPOSITORY}
                artifactid: ${ARTIFACTID}
                version: ${VERSION}
                project: ${PROJECT}
                profile: ${PROFILE}
        restart: 
            unless-stopped
        volumes:
            - rest-volume:/app/
        networks:
            - mynet
        ports:
            - "8080:8080"
        depends_on:
            - postgres
        env_file:
            - .env

networks:
  mynet:
    driver: bridge

volumes:
  postgres-volume:
  rest-volume: