version: '3'

services:
    postgres:
        container_name: 'pgsql'
        build: postgres/
        volumes:
            - postgres-volume:/var/lib/postgresql/data
        restart: 
            unless-stopped
        networks:
            - mynet
        ports:
            - "5432:5432"
        env_file:
            - .env
    rest:
        container_name: 'rest'
        build:
            context: .
            dockerfile: Dockerfile
            args:
                USERNAME_GIT: ${USERNAME_GIT}
                TAG: ${TAG}
                REPOSITORY: ${REPOSITORY}
                VERSION: ${VERSION}
                PROFILE: ${PROFILE}
        restart: 
            unless-stopped
        volumes:
            - rest-volume:/app/
        networks:
            - mynet
        ports:
            - "8080:8080"
        depends_on:
            - postgres
        env_file:
            - .env

networks:
  mynet:
    driver: bridge

volumes:
  postgres-volume:
  rest-volume: